from __future__ import annotations

from dataclasses import dataclass
from datetime import date, datetime


@dataclass(frozen=True)
class BacktestTrade:
    """
    Completed trade generated by a historical backtest strategy.
    """

    ticker: str
    entry_date: date | datetime | str
    exit_date: date | datetime | str
    entry_price: float
    exit_price: float
    shares: float = 1.0
    metadata: dict | None = None

    def __post_init__(self) -> None:
        if not str(self.ticker or "").strip():
            raise ValueError("BacktestTrade requires a ticker.")

        if self.entry_price <= 0:
            raise ValueError("BacktestTrade entry_price must be positive.")

        if self.exit_price < 0:
            raise ValueError("BacktestTrade exit_price cannot be negative.")

        if self.shares <= 0:
            raise ValueError("BacktestTrade shares must be positive.")

        if self.hold_days < 0:
            raise ValueError("BacktestTrade exit_date cannot be before entry_date.")

    @property
    def return_pct(self) -> float:
        return ((self.exit_price - self.entry_price) / self.entry_price) * 100.0

    @property
    def profit_loss(self) -> float:
        return (self.exit_price - self.entry_price) * self.shares

    @property
    def is_win(self) -> bool:
        return self.profit_loss > 0

    @property
    def hold_days(self) -> int:
        return (self._to_date(self.exit_date) - self._to_date(self.entry_date)).days

    @staticmethod
    def _to_date(value: date | datetime | str) -> date:
        if isinstance(value, datetime):
            return value.date()

        if isinstance(value, date):
            return value

        try:
            return datetime.fromisoformat(str(value)).date()
        except (TypeError, ValueError) as exc:
            raise ValueError("BacktestTrade dates must be date-like values.") from exc


@dataclass(frozen=True)
class BacktestStatistics:
    """
    Aggregate statistics for a deterministic backtest result.
    """

    total_trades: int = 0
    wins: int = 0
    losses: int = 0
    win_rate: float = 0.0
    average_gain: float = 0.0
    average_loss: float = 0.0
    expectancy: float = 0.0
    average_hold_days: float = 0.0
    max_drawdown: float = 0.0
    largest_winner: float = 0.0
    largest_loser: float = 0.0
